# Evolution API de {{NOMBRE}}. Generado por el provisioner.
COMPOSE_PROJECT_NAME=evo_{{SLUG}}

SERVER_NAME={{SLUG}}
SERVER_TYPE=http
SERVER_PORT=8080
SERVER_URL=http://127.0.0.1:{{PUERTO}}

TELEMETRY_ENABLED=false
LOG_LEVEL=ERROR,WARN,INFO
LOG_COLOR=false
LOG_BAILEYS=error
LANGUAGE=es

CORS_ORIGIN=*
CORS_METHODS=GET,POST,PUT,DELETE
CORS_CREDENTIALS=true

DEL_INSTANCE=false

DATABASE_PROVIDER=postgresql
DATABASE_CONNECTION_URI=postgresql://postgres:{{CLAVE_PG}}@evo-postgres:5432/evolution_db?schema=evolution_api
DATABASE_CONNECTION_CLIENT_NAME=evolution_exchange
DATABASE_SAVE_DATA_INSTANCE=true
DATABASE_SAVE_DATA_NEW_MESSAGE=true
DATABASE_SAVE_MESSAGE_UPDATE=true
DATABASE_SAVE_DATA_CONTACTS=true
DATABASE_SAVE_DATA_CHATS=true
DATABASE_SAVE_DATA_LABELS=true
DATABASE_SAVE_DATA_HISTORIC=true

CACHE_REDIS_ENABLED=true
CACHE_REDIS_URI=redis://evo-redis:6379/0
CACHE_REDIS_TTL=604800
CACHE_REDIS_PREFIX_KEY=evo_{{SLUG}}
CACHE_REDIS_SAVE_INSTANCES=false
CACHE_LOCAL_ENABLED=false

CHATWOOT_ENABLED=true
CHATWOOT_MESSAGE_READ=true
CHATWOOT_MESSAGE_DELETE=false
CHATWOOT_BOT_CONTACT=false
# Por nombre de contenedor y no por IP: la IP cambia al recrearse la red y el
# import queda roto sin avisar.
CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=postgresql://postgres:{{CLAVE_CHATWOOT_PG}}@chatsuite_{{SLUG}}-postgres-1:5432/chatwoot?sslmode=disable
CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=true

RABBITMQ_ENABLED=false
S3_ENABLED=false
WEBSOCKET_ENABLED=false

AUTHENTICATION_API_KEY={{APIKEY}}
AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=false

POSTGRES_PASSWORD={{CLAVE_PG}}
